cloud.aws.credentials.access-key=AKIAVE4AQSQKKSVPPRWC
cloud.aws.credentials.secret-key=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
cloud.aws.region.static=ap-south-1


aws.bucket.name=amazon-s3-demo-psuser